# -*- coding: utf-8 -*-
"""app_gradio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_Tx5gT-fyE0B2HH8Ia5tZITfLO6k_jW
"""

!pip install gradio

from tensorflow.keras.models import load_model

# Load the trained model
model = load_model("/content/model.h5")

import numpy as np
from PIL import Image

def predict_image(img):
    """
    img: PIL Image uploaded via Gradio
    returns: label + confidence
    """
    img = img.resize((150, 150))  # resize to model input
    img_array = np.array(img)/255.0  # normalize
    img_array = np.expand_dims(img_array, axis=0)  # add batch dimension

    prediction = model.predict(img_array)[0][0]
    label = "Dog 🐶" if prediction > 0.5 else "Cat 🐱"
    confidence = prediction if prediction > 0.5 else 1 - prediction
    return f"{label} ({confidence*100:.2f}%)"

import gradio as gr

# Define the Gradio interface
iface = gr.Interface(
    fn=predict_image,        # function to call
    inputs=gr.Image(type="pil"),  # upload images as PIL format
    outputs="text",          # output label + confidence
    title="🐶🐱 Dog vs Cat Classifier",
    description="Upload an image or screenshot of a cat or dog. The model will predict the class with confidence."
)

iface.launch()